# Generated by Django 4.1 on 2023-08-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0002_user_pfimg_tchprofile_stprofile_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leaveatch',
            field=models.FileField(upload_to='Attachments/'),
        ),
    ]
