# Generated by Django 4.1 on 2023-08-02 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LApp', '0004_alter_leave_appldate_alter_leave_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stprofile',
            name='sstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tchprofile',
            name='tstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='appldate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
